template-file-path: ./iam-lab-stack.yaml

parameters:
  PasswordLength: "16"
  SecretName: "iam-lab/temp-console-password"

tags:
  Project: IAMLab
  Environment: Lab
  ManagedBy: CloudFormation-GitSync
